# Generated by Django 5.0.14 on 2026-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kra_pin',
            field=models.CharField(blank=True, default='', help_text='Customer KRA PIN', max_length=20),
        ),
    ]
