# Generated by Django 5.0.14 on 2026-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quotation_payment_term',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('approved', 'Approved')], default='cash', max_length=20),
        ),
    ]
